# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: TylerAbele.com
email: tyler@tylerabele.com
description: > # this means to ignore newlines until "baseurl:"
  Pretty much a useless site, unless you're interested in me, my doings and happenings, coffee, some terrible side projects, or something else incredibly off the wall. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://tylerabele.com" # the base hostname & protocol for your site
twitter_username: TylerAbele
github_username:  tyabele
bitbucket_username: tyabele
# Build settings
markdown: kramdown
